src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Nom;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $checked;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function isChecked(): ?bool
    {
        return $this->checked;
    }

    public function setChecked(?bool $checked): self
    {
        $this->checked = $checked;

        return $this;
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TaskController extends AbstractController
{
    private TaskRepository $repo;

    // premier step, je sais que je vais ajouter et modifier, du coup tout ça est a taskrepository
    public function __construct(TaskRepository $repo)
    {
        $this->repo = $repo;
    }

    #[Route('/', name: 'task.create', methods: ['POST', 'GET'])]
    // despues de Request debo hacer ctl+clic para use Symfony\Component\HttpFoundation\Request;
    public function create(Request $request): Response
    {
        // request est tout ce que a ete envoye par la requette
        $submit = $request->get('submit');

        // pour recuperer la list de taches je dois declarer un variable, je crois une tableau $tasks
        $tasks = $this->repo->findAll();

        // je dois toujours verifier si le form a ete envoyé, , si submite n'existe pas alors
        // isset est pour savoir si le button a ete clique
        if (!isset($submit)) {
            // afiche les donnees et les coordonnees
            return $this->render('task/create.html.twig', ['mytasks' => $tasks]);
        }
        // dd('ici');

        // traitement des infos
        // trim est pour pas accepter les spaces
        $inputNewTask = trim($request->get('inputNewTask'));

        if (empty($inputNewTask)){
            return $this->render('task/create.html.twig', [
                'error'=>'La tâche est requis !',
                'mytask'=> $tasks
            ]);
        }

            $task = new Task();
        $task->setNom($inputNewTask)->setChecked(false);
        // dd($task);

        $this->repo->add($task, true);
        return $this->redirect('/');

        // la vieu qui sont toujours dans le templates, cet task est dans create, c'es la list de taches
        // return $this->render('task/create.html.twig', ['mytasks'=>$tasks]);
    }

    #[Route('/tasks/edit/{id}', methods: ['POST'])]
    // je dois passer le id dans le parametre parce que je le passe dans le URL
    public function update($id)
    {
            // je cherche la tache qui corresponde a cet id
        $task = $this->repo->find($id);
        // je veriefie si elle est fait au pas, en taskRepository veo que es boolean
        $task ->setChecked(!$task->isChecked());
        // j'appelle la methode update qui est a taskrepository
        $this->repo->update();
        // une fois fait je la redire vers la page d'accueil
        return $this->redirect('/');
    }

    #[Route('/tasks/{id}', methods:['POST'])]
    public function delete($id)
    {
        $task = $this->repo->find($id);
        $this->repo->remove($task, true);

        return $this->redirect('/');
    }

    #[Route('/tasks/delete/all', methods:['POST'])]
    public function deleteAll()
    {
        $this->repo->deleteAll();
        return $this->redirect('/');
    }
}

templates/layout/default.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}To-Do List
			{% endblock %}
		</title>
		<link rel="stylesheet" href="assets/css/style.css">
		{# <link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>"> #}
		<link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon">
        {# font awesome #}
		
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        
        {# google fonts #}
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link
		href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;500;700;900&display=swap" rel="stylesheet">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}{% endblock %}


	</head>
	<body>
		<main>
			{% block body %}{% endblock %}
		</main>


		{% block javascripts %}{% endblock %}
	</body>
</html>

templates/task/create.html.twig
{% extends "layout/default.html.twig" %}
{% block title %}
	To Do List

{% endblock %}

{% block body %}
	<div class="container">
		<h1>To do list</h1>
		{# action / est la diretion ou il va apres toucher le btn #}
		<form action="/" method="POST">
			<div class="container-input">
				<input
				class="input" type="text" name="inputNewTask" placeholder="New task">
				{# debo poner name  submite al button #}
				<button class="btnAdd btn" name="submit">ADD</button>
				{% if error is defined %}
					<div clas="error">{{error}}</div>
				{% endif %}
			</div>
		</form>

		<div class="container-task">
			{% if mytasks is not empty %}
			<div class="task">
				<ul>
					{% for task in mytasks %}
						
						<li>
							<div class="item">
								<form action="tasks/{{task.id}}" method="POST">
									<button onclick="return confirm('Do you want to delete this task?')" class="btnPoubelle">
										<i class="fa-solid fa-trash-can"></i>
									</button>
								</form>

								{# quand je vais faire un update, c'est bien d'ecrire edit dans le URL, je dois utiliser un form #}
								{# j'utilise le id de task #}
								<form action="/tasks/edit/{{task.id}}" method="POST">
									<button class="fait">
										{% if task.checked %}
											Fait
										{% else %}
											Pas fait
										{% endif %}
									</button>
								</form>
								<span {% if task.checked %} class="checked" {% endif %}>{{task.nom}}</span>
							</div>
						</li>
						
						{# le name ici est le name de l'input  #}

					{% endfor %}
				</ul>
			</div>
			<form action="tasks/delete/all" method="POST">
			{% if mytasks is not empty %}
			<button class="btn btnClear">Clear</button>
			{% endif %}
			</form>
			{% endif %}
		</div>
	</div>
{% endblock %}